apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-openchoreo-clustertrait
  title: ClusterTrait
  description: Define a cluster-wide reusable trait template to add cross-cutting capabilities like storage or observability to components across all namespaces.
spec:
  owner: openchoreo-users
  type: ClusterTrait
  # Enable user token injection for user-based authorization at OpenChoreo API
  EXPERIMENTAL_formDecorators:
    - id: openchoreo:inject-user-token
  parameters:
    - title: ClusterTrait Metadata
      required:
        - clustertrait_name
      properties:
        clustertrait_name:
          title: ClusterTrait Name
          type: string
          description: Name of the cluster trait (must be a valid Kubernetes name)
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Describe what this ClusterTrait is for
    - title: ClusterTrait Definition
      required:
        - yaml_definition
      properties:
        yaml_definition:
          title: ClusterTrait YAML
          type: string
          description: Edit the ClusterTrait YAML definition
          ui:field: ClusterTraitYamlEditor
  steps:
    - id: create-openchoreo-clustertrait
      name: Create OpenChoreo ClusterTrait
      action: openchoreo:clustertrait-definition:create
      input:
        yamlContent: ${{ parameters.yaml_definition }}
  output:
    links:
      - title: View ClusterTrait
        icon: catalog
        entityRef: ${{ steps['create-openchoreo-clustertrait'].output.entityRef }}
