apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-openchoreo-clustercomponenttype
  title: ClusterComponentType
  description: Define a cluster-wide reusable deployment pattern for how components are deployed across all namespaces.
spec:
  owner: openchoreo-users
  type: ClusterComponentType
  # Enable user token injection for user-based authorization at OpenChoreo API
  EXPERIMENTAL_formDecorators:
    - id: openchoreo:inject-user-token
  parameters:
    - title: ClusterComponentType Metadata
      required:
        - clustercomponenttype_name
      properties:
        clustercomponenttype_name:
          title: ClusterComponentType Name
          type: string
          description: Name of the cluster component type (must be a valid Kubernetes name)
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Describe what this ClusterComponentType is for
    - title: ClusterComponentType Definition
      required:
        - yaml_definition
      properties:
        yaml_definition:
          title: ClusterComponentType YAML
          type: string
          description: Edit the ClusterComponentType YAML definition
          ui:field: ClusterComponentTypeYamlEditor
  steps:
    - id: create-openchoreo-clustercomponenttype
      name: Create OpenChoreo ClusterComponentType
      action: openchoreo:clustercomponenttype-definition:create
      input:
        yamlContent: ${{ parameters.yaml_definition }}
  output:
    links:
      - title: View ClusterComponentType
        icon: catalog
        entityRef: ${{ steps['create-openchoreo-clustercomponenttype'].output.entityRef }}
